#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
ENV_FILE="${1:-$SCRIPT_DIR/lb.env}"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing env file: $ENV_FILE"
  echo "Tip: copy $SCRIPT_DIR/lb.env.example to $SCRIPT_DIR/lb.env"
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

LB_DOMAIN="${LB_DOMAIN:-}"
LB_STRATEGY="${LB_STRATEGY:-least_conn}"
BACKEND_NODES="${BACKEND_NODES:-}"
UPSTREAM_NAME="${UPSTREAM_NAME:-token_exam_backend}"
ENABLE_TLS="${ENABLE_TLS:-false}"
TLS_CERT_PATH="${TLS_CERT_PATH:-}"
TLS_KEY_PATH="${TLS_KEY_PATH:-}"
OUTPUT_PATH="${OUTPUT_PATH:-/etc/nginx/sites-available/token-lb.conf}"

if [[ -z "$LB_DOMAIN" ]]; then
  echo "LB_DOMAIN is required"
  exit 1
fi

if [[ -z "$BACKEND_NODES" ]]; then
  echo "BACKEND_NODES is required"
  exit 1
fi

case "$LB_STRATEGY" in
  least_conn|round_robin|ip_hash) ;;
  *)
    echo "Invalid LB_STRATEGY: $LB_STRATEGY"
    echo "Allowed: least_conn, round_robin, ip_hash"
    exit 1
    ;;
esac

IFS=',' read -r -a NODE_ARRAY <<< "$BACKEND_NODES"
if [[ ${#NODE_ARRAY[@]} -eq 0 ]]; then
  echo "No backend nodes parsed from BACKEND_NODES"
  exit 1
fi

for node in "${NODE_ARRAY[@]}"; do
  node_trimmed="$(echo "$node" | xargs)"
  if [[ ! "$node_trimmed" =~ ^[^:]+:[0-9]+$ ]]; then
    echo "Invalid backend format: $node_trimmed"
    echo "Expected host:port,host:port"
    exit 1
  fi
done

build_strategy_line() {
  case "$LB_STRATEGY" in
    least_conn) echo "    least_conn;" ;;
    ip_hash) echo "    ip_hash;" ;;
    round_robin) echo "" ;;
  esac
}

build_backend_lines() {
  for node in "${NODE_ARRAY[@]}"; do
    node_trimmed="$(echo "$node" | xargs)"
    echo "    server ${node_trimmed} max_fails=3 fail_timeout=10s;"
  done
}

mkdir -p "$(dirname "$OUTPUT_PATH")"

cat > "$OUTPUT_PATH" <<EOF
# Auto-generated by scripts/lb/generate-nginx-lb.sh
# Source env: $ENV_FILE

upstream $UPSTREAM_NAME {
$(build_strategy_line)
$(build_backend_lines)

    keepalive 64;
}

server {
    listen 80;
    server_name $LB_DOMAIN;

    client_max_body_size 20m;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Connection "";

        proxy_connect_timeout 5s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
        proxy_next_upstream_tries 3;

        proxy_pass http://$UPSTREAM_NAME;
    }

    location = /lb-health {
        add_header Content-Type text/plain;
        return 200 "ok\\n";
    }
}
EOF

if [[ "$ENABLE_TLS" == "true" ]]; then
  if [[ -z "$TLS_CERT_PATH" || -z "$TLS_KEY_PATH" ]]; then
    echo "ENABLE_TLS=true requires TLS_CERT_PATH and TLS_KEY_PATH"
    exit 1
  fi

  cat >> "$OUTPUT_PATH" <<EOF

server {
    listen 443 ssl http2;
    server_name $LB_DOMAIN;

    ssl_certificate $TLS_CERT_PATH;
    ssl_certificate_key $TLS_KEY_PATH;

    client_max_body_size 20m;

    location / {
        proxy_http_version 1.1;
        proxy_set_header Host \$host;
        proxy_set_header X-Real-IP \$remote_addr;
        proxy_set_header X-Forwarded-For \$proxy_add_x_forwarded_for;
        proxy_set_header X-Forwarded-Proto \$scheme;
        proxy_set_header Connection "";

        proxy_connect_timeout 5s;
        proxy_send_timeout 60s;
        proxy_read_timeout 60s;

        proxy_next_upstream error timeout http_500 http_502 http_503 http_504;
        proxy_next_upstream_tries 3;

        proxy_pass http://$UPSTREAM_NAME;
    }
}
EOF
fi

echo "[OK] Generated nginx LB config: $OUTPUT_PATH"
