#!/usr/bin/env bash
set -euo pipefail

SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
DRY_RUN=false
ENV_FILE=""

for arg in "$@"; do
  case "$arg" in
    --dry-run)
      DRY_RUN=true
      ;;
    *)
      if [[ -z "$ENV_FILE" ]]; then
        ENV_FILE="$arg"
      else
        echo "Unexpected argument: $arg"
        echo "Usage: $0 [path/to/lb.env] [--dry-run]"
        exit 1
      fi
      ;;
  esac
done

ENV_FILE="${ENV_FILE:-$SCRIPT_DIR/lb.env}"

if [[ ! -f "$ENV_FILE" ]]; then
  echo "Missing env file: $ENV_FILE"
  echo "Tip: copy $SCRIPT_DIR/lb.env.example to $SCRIPT_DIR/lb.env"
  exit 1
fi

# shellcheck disable=SC1090
source "$ENV_FILE"

LB_DOMAIN="${LB_DOMAIN:-}"
LB_STRATEGY="${LB_STRATEGY:-least_conn}"
BACKEND_NODES="${BACKEND_NODES:-}"
HAPROXY_BACKEND_NAME="${HAPROXY_BACKEND_NAME:-be_token_apps}"
HEALTH_CHECK_PATH="${HEALTH_CHECK_PATH:-/api/config/health}"
HAPROXY_OUTPUT_PATH="${HAPROXY_OUTPUT_PATH:-/etc/haproxy/haproxy.cfg}"

if [[ -z "$LB_DOMAIN" ]]; then
  echo "LB_DOMAIN is required"
  exit 1
fi

if [[ -z "$BACKEND_NODES" ]]; then
  echo "BACKEND_NODES is required"
  exit 1
fi

case "$LB_STRATEGY" in
  least_conn|round_robin|ip_hash) ;;
  *)
    echo "Invalid LB_STRATEGY: $LB_STRATEGY"
    echo "Allowed: least_conn, round_robin, ip_hash"
    exit 1
    ;;
esac

IFS=',' read -r -a NODE_ARRAY <<< "$BACKEND_NODES"
if [[ ${#NODE_ARRAY[@]} -eq 0 ]]; then
  echo "No backend nodes parsed from BACKEND_NODES"
  exit 1
fi

for node in "${NODE_ARRAY[@]}"; do
  node_trimmed="$(echo "$node" | xargs)"
  if [[ ! "$node_trimmed" =~ ^[^:]+:[0-9]+$ ]]; then
    echo "Invalid backend format: $node_trimmed"
    echo "Expected host:port,host:port"
    exit 1
  fi
done

build_balance_line() {
  case "$LB_STRATEGY" in
    least_conn) echo "    balance leastconn" ;;
    round_robin) echo "    balance roundrobin" ;;
    ip_hash) echo "    balance source" ;;
  esac
}

build_server_lines() {
  local idx=1
  for node in "${NODE_ARRAY[@]}"; do
    local node_trimmed
    node_trimmed="$(echo "$node" | xargs)"
    echo "    server app${idx} ${node_trimmed} check"
    idx=$((idx + 1))
  done
}

render_config() {
cat <<EOF
# Auto-generated by scripts/lb/generate-haproxy-lb.sh
# Source env: $ENV_FILE

global
    log /dev/log local0
    log /dev/log local1 notice
    daemon
    maxconn 4000

defaults
    log global
    mode http
    option httplog
    timeout connect 5s
    timeout client 60s
    timeout server 60s
    retries 3

frontend fe_token_http
    bind *:80
    http-request set-header X-Forwarded-Proto http
    acl host_ok hdr(host) -i ${LB_DOMAIN}
    http-request deny deny_status 400 unless host_ok
    default_backend ${HAPROXY_BACKEND_NAME}

backend ${HAPROXY_BACKEND_NAME}
$(build_balance_line)
    option httpchk GET ${HEALTH_CHECK_PATH}
    http-check expect status 200
$(build_server_lines)
EOF
}

if [[ "$DRY_RUN" == "true" ]]; then
  render_config
  exit 0
fi

mkdir -p "$(dirname "$HAPROXY_OUTPUT_PATH")"
render_config > "$HAPROXY_OUTPUT_PATH"

echo "[OK] Generated HAProxy LB config: $HAPROXY_OUTPUT_PATH"
